### ISSUE TITLE
Docusaurus: Update available 2.0.0-beta.9 → 3.1.1    

### ISSUE THREAD

**Issue by luke-** [humhub/documentation#99]
We should upgrade to the last Docusaurus.

It would be important to find out whether we need to make changes here, e.g. to the layout etc. 

```   ╭────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                        │
   │                         Update available 2.0.0-beta.9 → 3.1.1                          │
   │                                                                                        │
   │   To upgrade Docusaurus packages with the latest version, run the following command:   │
   │         yarn upgrade @docusaurus/core@latest @docusaurus/preset-classic@latest         │
   │                                                                                        │
   ╰────────────────────────────────────────────────────────────────────────────────────────╯

```

**Comment by luke-** [comment]
@serh-mosk Would this be a task for you?

**Comment by luke-** [comment]
@serh-mosk Thanks for the fast PR. When running `npm install` on a clean checkout of your branch, I'm getting following error:

```
documentation git:(updated-docusaurus-to-3.1.1) npm install
npm WARN old lockfile
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile
npm WARN old lockfile Error: Integrity checksum failed when using sha512: wanted sha512-BBruZFWmt3HFdVPS8kceTBIguKxu4f99n5JNp06OlPD/luoAMIaIK5ieV5YjnBLH3Nysai9sxj9rpJj4ZisXOA== but got sha512-acWTYaha8xfhA/Du/z4sNZjHUWjkiuoAi2LM+T/aL+kemKQgPT1xBb/YKjlQ0Qo8gvbHsGNplrEJ+9G3gL7i4Q==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:163:35)
npm WARN old lockfile     at async /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:749:24
npm WARN old lockfile  Could not fetch metadata for caniuse-lite@1.0.30001583 Error: Integrity checksum failed when using sha512: wanted sha512-BBruZFWmt3HFdVPS8kceTBIguKxu4f99n5JNp06OlPD/luoAMIaIK5ieV5YjnBLH3Nysai9sxj9rpJj4ZisXOA== but got sha512-acWTYaha8xfhA/Du/z4sNZjHUWjkiuoAi2LM+T/aL+kemKQgPT1xBb/YKjlQ0Qo8gvbHsGNplrEJ+9G3gL7i4Q==.
npm WARN old lockfile     at RegistryFetcher.manifest (/usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:163:35)
npm WARN old lockfile     at async /usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:749:24 {
npm WARN old lockfile   code: 'EINTEGRITY'
npm WARN old lockfile }
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: humhub-doc@0.0.0
npm ERR! Found: @docusaurus/core@2.0.0-beta.8
npm ERR! node_modules/@docusaurus/core
npm ERR!   @docusaurus/core@"3.1.1" from the root project
npm ERR!   @docusaurus/core@"2.0.0-beta.8" from @docusaurus/mdx-loader@2.0.0-beta.8
npm ERR!   node_modules/@docusaurus/mdx-loader
npm ERR!     @docusaurus/mdx-loader@"2.0.0-beta.8" from @docusaurus/plugin-content-blog@2.0.0-beta.8
npm ERR!     node_modules/@docusaurus/plugin-content-blog
npm ERR!       @docusaurus/plugin-content-blog@"2.0.0-beta.8" from @docusaurus/theme-common@2.0.0-beta.8
npm ERR!       node_modules/@docusaurus/theme-common
npm ERR!         @docusaurus/theme-common@"2.0.0-beta.8" from @docusaurus/theme-classic@2.0.0-beta.8
npm ERR!         node_modules/@docusaurus/theme-classic
npm ERR!         1 more (@docusaurus/theme-search-algolia)
npm ERR!       2 more (@docusaurus/theme-classic, @docusaurus/preset-classic)
npm ERR!     @docusaurus/mdx-loader@"2.0.0-beta.8" from @docusaurus/plugin-content-docs@2.0.0-beta.8
npm ERR!     node_modules/@docusaurus/plugin-content-docs
npm ERR!       @docusaurus/plugin-content-docs@"2.0.0-beta.8" from @docusaurus/theme-common@2.0.0-beta.8
npm ERR!       node_modules/@docusaurus/theme-common
npm ERR!         @docusaurus/theme-common@"2.0.0-beta.8" from @docusaurus/theme-classic@2.0.0-beta.8
npm ERR!         node_modules/@docusaurus/theme-classic
npm ERR!         1 more (@docusaurus/theme-search-algolia)
npm ERR!       2 more (@docusaurus/theme-classic, @docusaurus/preset-classic)
npm ERR!     1 more (@docusaurus/plugin-content-pages)
npm ERR!   11 more (@docusaurus/plugin-content-blog, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @docusaurus/core@"3.1.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.0.0" from @docusaurus/core@3.1.1
npm ERR!   node_modules/@docusaurus/core
npm ERR!     @docusaurus/core@"3.1.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

Any idea?

**Comment by serh-mosk** [comment]
@luke- I fixed package-lock.json and yarn.lock. Try to install now.

**Comment by luke-** [comment]
@serh-mosk Thank you, now it works.

```
➜  documentation git:(updated-docusaurus-to-3.1.1) ✗ npm install

up to date, audited 1212 packages in 2s

286 packages are looking for funding
  run `npm fund` for details

5 vulnerabilities (3 high, 2 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
```

Can you check the warnings as well please?

After running `npm run start` i get following errors: 

![image](https://github.com/humhub/documentation/assets/4736168/4f423625-a0a3-4bbf-bf9d-69546dce62eb)

Any idea?

Thanks!

**Comment by luke-** [comment]
@serh-mosk Thanks, it's working fine now and I've already deployed it to docs.humhub.org
